{% set version = '3.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggtern
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggtern_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggtern/ggtern_{{ version }}.tar.gz
  sha256: a3190857abdbbb2548505f774f91cb34be0d680ae462b5c0a5efea9f28ae9d8a

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-compositions >=1.40_2
    - r-ggplot2 >=3.3.0
    - r-gridextra
    - r-gtable >=0.1.2
    - r-hexbin
    - r-latex2exp >=0.4
    - r-lattice
    - r-plyr >=1.8.3
    - r-proto
    - r-scales >=0.3.0
  run:
    - r-base
    - r-mass
    - r-compositions >=1.40_2
    - r-ggplot2 >=3.3.0
    - r-gridextra
    - r-gtable >=0.1.2
    - r-hexbin
    - r-latex2exp >=0.4
    - r-lattice
    - r-plyr >=1.8.3
    - r-proto
    - r-scales >=0.3.0

test:
  commands:
    - $R -e "library('ggtern')"           # [not win]
    - "\"%R%\" -e \"library('ggtern')\""  # [win]

about:
  home: http://www.ggtern.com
  license: GPL-2
  summary: Extends the functionality of 'ggplot2', providing the capability to plot ternary diagrams
    for (subset of) the 'ggplot2' geometries. Additionally, 'ggtern' has implemented
    several NEW geometries which are unavailable to the standard 'ggplot2' release.
    For further examples and documentation, please proceed to the 'ggtern' website.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo

# Package: ggtern
# Version: 3.3.0
# Date: 2020-04-9
# Title: An Extension to 'ggplot2', for the Creation of Ternary Diagrams
# Description: Extends the functionality of 'ggplot2', providing the capability to plot ternary diagrams for (subset of) the 'ggplot2' geometries. Additionally, 'ggtern' has implemented several NEW geometries which are unavailable to the standard 'ggplot2' release. For further examples and documentation, please proceed to the 'ggtern' website.
# Authors@R: person("Nicholas","Hamilton", ,"nick@ggtern.com", role = c("aut", "cre"))
# Author: Nicholas Hamilton [aut, cre]
# Maintainer: Nicholas Hamilton <nick@ggtern.com>
# Depends: R (>= 2.10), ggplot2 (>= 3.3.0)
# Imports: compositions (>= 1.40-2), grid, gridExtra, gtable (>= 0.1.2), latex2exp (>= 0.4), MASS, plyr (>= 1.8.3), scales (>= 0.3.0), stats, proto, utils, lattice, hexbin
# Enhances: sp
# License: GPL-2 | file LICENSE
# Encoding: UTF-8
# URL: http://www.ggtern.com
# Collate: 'ggtern-package.R' 'aes.R' 'coord-tern.R' 'calc-tern-tlr2xy.R' 'calc-mahalanobis-distance.R' 'calc-kde2d-weighted.R' 'doc-data.R' 'doc-theme-convenience.R' 'depreciated.R' 'labels-new.R' 'labels-percent.R' 'legend-draw-tern.R' 'ggtern-constructor.R' 'gg-internal.R' 'modifications-gridExtra.R' 'onLoad.R' 'plot.R' 'plot-build.R' 'plot-construction.R' 'position-.R' 'position-nudge-tern.R' 'position-jitter-tern.R' 'save.R' 'scales-tern.R' 'strip-unapproved.R' 'tern-limits.R' 'theme.R' 'theme-arrowlength.R' 'theme-clockwise.R' 'theme-defaults.R' 'theme-elements.R' 'theme-gridsontop.R' 'theme-bordersontop.R' 'theme-legend-position.R' 'theme-latex.R' 'theme-mesh.R' 'theme-noarrows.R' 'theme-nomask.R' 'theme-novar-tern.R' 'theme-rotate.R' 'theme-showgrid.R' 'theme-showlabels.R' 'theme-ticks.R' 'theme-showtitles.R' 'theme-ticksoutside.R' 'theme-zoom.R' 'utilities.R' 'utilities-help.R' 'geom-density-tern.R' 'stat-density-tern.R' 'geom-mask.R' 'geom-Xline.R' 'geom-Xisoprop.R' 'geom-confidence-tern.R' 'stat-confidence-tern.R' 'geom-errorbarX.R' 'geom-smooth-tern.R' 'stat-smooth-tern.R' 'geom-mean-ellipse.R' 'stat-mean-ellipse.R' 'geom-interpolate-tern.R' 'stat-interpolate-tern.R' 'stat-interpolate-methods.R' 'geom-crosshair-tern.R' 'geom-point-swap.R' 'geom-hex-tern.R' 'stat-hex-tern.R' 'annotation-tern.R' 'annotation-raster-tern.R' 'geom-text-viewport.R' 'geom-label-viewport.R' 'geom-polygon-closed.R' 'geom-tri-tern.R' 'stat-tri-tern.R'
# NeedsCompilation: no
# Repository: CRAN
# RoxygenNote: 6.1.1
# Packaged: 2020-04-11 08:27:40 UTC; nick
# Date/Publication: 2020-04-11 14:50:05 UTC
