{% set version = "3.4.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggtern
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggtern_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggtern/ggtern_{{ version }}.tar.gz
  sha256: c1782036d7ed915657bb9cd4e90f3e80c85c139563f545e59b3ff780e203b0f6

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-compositions >=2.0_2
    - r-ggplot2 >=3.4.0
    - r-gridextra >=2.3
    - r-gtable >=0.1.2
    - r-hexbin >=1.28.2
    - r-latex2exp >=0.5
    - r-lattice
    - r-plyr >=1.8.3
    - r-proto >=1.0
    - r-scales >=0.3.0
  run:
    - r-base
    - r-mass
    - r-compositions >=2.0_2
    - r-ggplot2 >=3.4.0
    - r-gridextra >=2.3
    - r-gtable >=0.1.2
    - r-hexbin >=1.28.2
    - r-latex2exp >=0.5
    - r-lattice
    - r-plyr >=1.8.3
    - r-proto >=1.0
    - r-scales >=0.3.0

test:
  commands:
    - $R -e "library('ggtern')"           # [not win]
    - "\"%R%\" -e \"library('ggtern')\""  # [win]

about:
  home: http://www.ggtern.com
  dev_url: https://bitbucket.org/nicholasehamilton/ggtern/
  license: GPL-2.0-only
  summary: Extends the functionality of 'ggplot2', providing the capability to plot ternary diagrams for (subset of) the 'ggplot2' geometries. Additionally, 'ggtern' has implemented several NEW geometries which are unavailable to the standard 'ggplot2' release. For further examples and documentation, please proceed to the
    'ggtern' website.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo
